export const ADD_COCKTAIL = "ADD_COCKTAIL";

export const GET_COCKTAIL_REQUESTED = "GET_COCKTAIL_REQUESTED";
export const GET_COCKTAIL_SUCCESS = "GET_COCKTAIL_SUCCESS";
export const GET_COCKTAIL_FAILED = "GET_COCKTAIL_FAILED";